require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuffaloesController do

  # This should return the minimal set of attributes required to create a valid
  # Buffalo. As you add validations to Buffalo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "uid" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuffaloesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all buffaloes as @buffaloes" do
      buffalo = Buffalo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:buffaloes).should eq([buffalo])
    end
  end

  describe "GET show" do
    it "assigns the requested buffalo as @buffalo" do
      buffalo = Buffalo.create! valid_attributes
      get :show, {:id => buffalo.to_param}, valid_session
      assigns(:buffalo).should eq(buffalo)
    end
  end

  describe "GET new" do
    it "assigns a new buffalo as @buffalo" do
      get :new, {}, valid_session
      assigns(:buffalo).should be_a_new(Buffalo)
    end
  end

  describe "GET edit" do
    it "assigns the requested buffalo as @buffalo" do
      buffalo = Buffalo.create! valid_attributes
      get :edit, {:id => buffalo.to_param}, valid_session
      assigns(:buffalo).should eq(buffalo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Buffalo" do
        expect {
          post :create, {:buffalo => valid_attributes}, valid_session
        }.to change(Buffalo, :count).by(1)
      end

      it "assigns a newly created buffalo as @buffalo" do
        post :create, {:buffalo => valid_attributes}, valid_session
        assigns(:buffalo).should be_a(Buffalo)
        assigns(:buffalo).should be_persisted
      end

      it "redirects to the created buffalo" do
        post :create, {:buffalo => valid_attributes}, valid_session
        response.should redirect_to(Buffalo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved buffalo as @buffalo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Buffalo.any_instance.stub(:save).and_return(false)
        post :create, {:buffalo => { "uid" => "invalid value" }}, valid_session
        assigns(:buffalo).should be_a_new(Buffalo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Buffalo.any_instance.stub(:save).and_return(false)
        post :create, {:buffalo => { "uid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested buffalo" do
        buffalo = Buffalo.create! valid_attributes
        # Assuming there are no other buffaloes in the database, this
        # specifies that the Buffalo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Buffalo.any_instance.should_receive(:update).with({ "uid" => "MyString" })
        put :update, {:id => buffalo.to_param, :buffalo => { "uid" => "MyString" }}, valid_session
      end

      it "assigns the requested buffalo as @buffalo" do
        buffalo = Buffalo.create! valid_attributes
        put :update, {:id => buffalo.to_param, :buffalo => valid_attributes}, valid_session
        assigns(:buffalo).should eq(buffalo)
      end

      it "redirects to the buffalo" do
        buffalo = Buffalo.create! valid_attributes
        put :update, {:id => buffalo.to_param, :buffalo => valid_attributes}, valid_session
        response.should redirect_to(buffalo)
      end
    end

    describe "with invalid params" do
      it "assigns the buffalo as @buffalo" do
        buffalo = Buffalo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Buffalo.any_instance.stub(:save).and_return(false)
        put :update, {:id => buffalo.to_param, :buffalo => { "uid" => "invalid value" }}, valid_session
        assigns(:buffalo).should eq(buffalo)
      end

      it "re-renders the 'edit' template" do
        buffalo = Buffalo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Buffalo.any_instance.stub(:save).and_return(false)
        put :update, {:id => buffalo.to_param, :buffalo => { "uid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested buffalo" do
      buffalo = Buffalo.create! valid_attributes
      expect {
        delete :destroy, {:id => buffalo.to_param}, valid_session
      }.to change(Buffalo, :count).by(-1)
    end

    it "redirects to the buffaloes list" do
      buffalo = Buffalo.create! valid_attributes
      delete :destroy, {:id => buffalo.to_param}, valid_session
      response.should redirect_to(buffaloes_url)
    end
  end

end
